version: "3"
services:
  proxy:
    build: proxy
    restart: on-failure
    ports:
      - 8888:8888
      - 9901:9901
  backend_tests:
    build: backend
    volumes:
      - "./backend:/app"
    command: bash -c "find src -name '**.py' | ENTR_INOTIFY_WORKAROUND=1 entr -d pytest src"
    restart: on-failure
  backend:
    build: backend
    environment:
      MEDIA_SERVER_SECRET_KEY: 1c40f0f493eea6e0c2dec15c8c1d32c25f2f4b4dacf3a7a255d8d2ab56fa9677
      MEDIA_SERVER_BEARER_TOKEN: aabbcbaa02883911
      AWS_PROFILE: coucherscreds
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - "./backend:/app"
    # see https://github.com/eradman/entr#docker-and-windows-subsystem-for-linux
    command: bash -c "find src -name '**.py' | ENTR_INOTIFY_WORKAROUND=1 entr -rd python src/app.py"
    restart: on-failure
    ports:
      - 1751:1751
      - 1752:1752
      - 1753:1753
  media_tests:
    build: media
    command: pytest src
    restart: on-failure
    environment:
      MEDIA_SERVER_FROM_ENV: 0
  media:
    build: media
    environment:
      MAIN_SERVER_ADDRESS: "backend:1753"
      MEDIA_SERVER_SECRET_KEY: 1c40f0f493eea6e0c2dec15c8c1d32c25f2f4b4dacf3a7a255d8d2ab56fa9677
      MEDIA_SERVER_BEARER_TOKEN: aabbcbaa02883911
      MAIN_SERVER_USE_SSL: 0
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - backend
    links:
      - backend
  frontend:
    build: frontend
    volumes:
      - "./frontend:/app"
    command: yarn dev
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - backend
    links:
      - backend
